<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-U9KGDGS" name="runners.LoginRunner_Test" tests="1" failures="0" timestamp="29 Jul 2019 20:31:40 GMT" time="6.841" errors="1">
  <testcase name="feature" time="6.841" classname="runners.LoginRunner_Test">
    <error type="cucumber.runtime.CucumberException" message="cucumber.runtime.CucumberException: Arity mismatch: Step Definition &#039;stepDefinitions.loginScenarios.user_enters_following_credentials_for_login() in file:/C:/Users/musta/eclipse-workspace/cafetownsend/target/classes/&#039; with pattern [^User enters following credentials for login$] is declared with 0 parameters. However, the gherkin step has 1 arguments [Table:[[username, password], [Luke, Skywalker]]]. 
Step: And User enters following credentials for login">
      <![CDATA[cucumber.runtime.CucumberException: cucumber.runtime.CucumberException: Arity mismatch: Step Definition 'stepDefinitions.loginScenarios.user_enters_following_credentials_for_login() in file:/C:/Users/musta/eclipse-workspace/cafetownsend/target/classes/' with pattern [^User enters following credentials for login$] is declared with 0 parameters. However, the gherkin step has 1 arguments [Table:[[username, password], [Luke, Skywalker]]]. 
Step: And User enters following credentials for login
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: cucumber.runtime.CucumberException: Arity mismatch: Step Definition 'stepDefinitions.loginScenarios.user_enters_following_credentials_for_login() in file:/C:/Users/musta/eclipse-workspace/cafetownsend/target/classes/' with pattern [^User enters following credentials for login$] is declared with 0 parameters. However, the gherkin step has 1 arguments [Table:[[username, password], [Luke, Skywalker]]]. 
Step: And User enters following credentials for login
	at cucumber.runtime.StepDefinitionMatch.arityMismatch(StepDefinitionMatch.java:102)
	at cucumber.runtime.StepDefinitionMatch.transformedArgs(StepDefinitionMatch.java:60)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:300)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
	... 25 more
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- runners.LoginRunner_Test -->
